version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: unit test
          command: cargo test --all
  dev-build:
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - checkout
      - run:
          name: build a binary
          command: cargo build --release

workflows:
  version: 2
  pr:
    jobs:
      - unit-test
      - dev-build
