[package]
name = "famo-archive"
version = "0.1.0"
authors = ["tbrand <taichiro0709@gmail.com>"]

[dependencies]
tar = "*"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
failure = "*"